--- 
clone: 
  depth: 1
kind: pipeline
name: azrimPipeline
steps: 
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands: 
      - "curl https://raw.githubusercontent.com/Chuck439/script/master/kernel/buildnojava | bash"
    image: azrim89/kernel:latest
    name: Build
    trigger: 
      branch: 
        - staging
